name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t flask-app-ao13 .

    - name: Run Docker container
      id: run_container
      run: |
        docker run -d -p 80:5000 --name flask-app-ao13 flask-app-ao13

    - name: Get container IP address
      run: |
        container_id=$(docker ps -qf "name=flask-app-ao13")
        container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
        echo "Container IP Address: $container_ip"
        echo "::set-output name=container_ip::$container_ip"

    - name: Print container IP
      run: |
        container_id=$(docker ps -qf "name=flask-app-ao13")
        container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
        echo "The Flask app is running at http://$container_ip:80"
