name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t my-flask-app-container .
        docker tag my-flask-app-container:latest ${{ secrets.DOCKER_USERNAME }}/my-flask-app-container:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app-container:latest

    - name: Deploy Docker container
      run: |
        docker run -d -p 8080:5000 --name my-flask-app-container ${{ secrets.DOCKER_USERNAME }}/my-flask-app-container:latest

    - name: Verify deployment
      run: |
        curl http://localhost:8080
